<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonLoginFromHomePage</name>
   <tag></tag>
   <elementGuidId>f943433c-99ce-45f5-bdf8-44bb2fae30ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-test = 'nav-sign-in']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-test=&quot;nav-sign-in&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;nav-sign-in&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7fadb2b-50d1-4a68-8db5-4499d9ea94ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>nav-sign-in</value>
      <webElementGuid>b801a8b4-a311-47b1-8cfa-23cbe3993237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/auth/login</value>
      <webElementGuid>216d5293-e5d6-4b3c-a572-331d846a619a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>43561489-f17b-48fe-9dc4-73d367ef71f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/login</value>
      <webElementGuid>8c2b2372-6217-491d-81e7-419bd59bbfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>970641a8-df9d-4c48-929d-84c14b7e7de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0197dc04875572fdb0cfb7f64fdaa66f</value>
      <webElementGuid>d251ca30-3c1f-48af-be28-9e770485aaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-test = 'nav-sign-in']</value>
      <webElementGuid>3ab8f8f2-9d71-4d24-916f-8b46aed17feb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-test = 'nav-sign-in']</value>
      <webElementGuid>321b282d-07eb-4a39-b531-01f6e6bdc803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/login' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>3a3e829c-615b-4f3c-9f7a-b8e78274afa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
