<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelPostalCode</name>
   <tag></tag>
   <elementGuidId>6de86692-5ecc-44d5-be9a-1ca51425f04a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@for = 'postal_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;postal_code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Postal code&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>32bec5b7-3bb8-4017-9cba-d2cc68fb831c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>postal_code</value>
      <webElementGuid>238e64b3-ecc5-41f0-b036-4295516d7e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>64c24f6d-0eb8-4d71-ac7e-73dc545ec122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Postal code</value>
      <webElementGuid>e26f0a39-f6fb-4caa-b6a8-0f045967d36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ae13e67057e89e99c7fe296b688c4221</value>
      <webElementGuid>112000ec-ce00-4cf2-a71c-18057233d4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'postal_code']</value>
      <webElementGuid>2ebaafd0-8f2a-4856-8ce0-1b75d0e7029f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@for = 'postal_code']</value>
      <webElementGuid>4655a40a-3202-4c5d-9487-39a5e6ca84b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Postal code' or . = 'Postal code')]</value>
      <webElementGuid>645a5d9d-f052-4360-a2e7-0f4c2f95d4b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
