<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelHouseNumber</name>
   <tag></tag>
   <elementGuidId>2f49e554-8857-452f-ad73-228862d9df81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@for = 'house_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;house_number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;House number&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3c4f7e9d-bfc4-40e7-aa76-0161a27d3d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>house_number</value>
      <webElementGuid>ccfc53cf-485e-4f3c-b60d-bfa0ec31fc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>86a316ac-2228-4251-b515-e5533ec09a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>House number</value>
      <webElementGuid>1ba4ebac-a10d-4e53-908c-35cc5e746753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d866058721dcf0bec8a25b4b5871d61b</value>
      <webElementGuid>a9f739db-0ced-40ce-8abf-382f2f8812ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'house_number']</value>
      <webElementGuid>d982a3db-47f4-4240-8b14-720b2cb8d9a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@for = 'house_number']</value>
      <webElementGuid>3c5996cd-7f3c-41ed-9ad4-5b3a9af23bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'House number' or . = 'House number')]</value>
      <webElementGuid>63185ad8-b129-4856-bbf3-d5edb9766ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
