<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>headerMyAccount</name>
   <tag></tag>
   <elementGuidId>1cbb39cb-531a-4a6f-9628-a55289345b3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-test = 'page-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-test=&quot;page-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;page-title&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>19e35ba6-5a4c-4c26-a468-3235d4f2f8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>10f1da79-b2dd-4534-b742-593cb3425a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My account</value>
      <webElementGuid>41f85a98-3adc-44dd-86f7-8bceaacae8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-69ef0159dc547498b1d42f1347919ce2</value>
      <webElementGuid>d22109e0-bb0c-4ad4-9e7c-9ae90d0a59fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-test = 'page-title']</value>
      <webElementGuid>e7085eb4-3a4a-4c12-8db1-0788740b70d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-test = 'page-title']</value>
      <webElementGuid>eac12850-eced-4b8c-8da1-b47ff648b351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'My account' or . = 'My account')]</value>
      <webElementGuid>90e094c2-7b4f-4291-b172-718b6f9bf022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
